### ISSUE TITLE
`Promise.prototype.finally` requires a global `Promise` be available

### ISSUE THREAD

**Issue by zvictor** [es-shims/Promise.prototype.finally#1]
Running the shim in a Chrome Version 52.0.2743.116 (64-bit) raises an error complaining about the lack of a global `Promise` function.

```js
requirePromise.js:5 Uncaught TypeError: `Promise.prototype.finally` requires a global `Promise` be available.
```

Given that there is definitely such function there, shouldn't the code `requirePromise.js` look further for it?
Wouldn't it be appropriate to change the verification to something like the following?

```js
if (typeof (Promise || global.Promise || window.Promise) !== 'function') {
	throw ...
}
```

**Comment by ljharb** [comment]
Can you provide a jsfiddle that reproduces this? Otherwise, I think this should be closed.

**Comment by pornel** [comment]
AFAIK `typeof Promise` is the correct way to check for presence of global `Promise`, so the problem might be elsewhere (maybe a JS minifier incorrectly renamed variables?) 

The proposed change would break the code, because it's equivalent to:

```js
let tmp = (Promise || global.Promise || window.Promise);
if (typeof tmp …
```

and it'd cause `ReferenceError` when the global `Promise` does not exist.
